name: Action Test Workflow

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Hello World Job
    steps:

    - uses: actions/checkout@v2

    - name: Greeting step
      uses: GuillaumeFalourd/poc-composite-run-steps-action@main
      with:
        who-to-greet: 'Mona the Octocat'

    - name: Generating random number step
      run: echo random-number ${{ steps.foo.outputs.random-number }}
      shell: bash
